spring.application.name=taskmanager
spring.datasource.url=jdbc:mysql://localhost:3306/taskdb
spring.datasource.username=root
spring.datasource.password=saitama@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
